### ISSUE TITLE
UPMでインストールしたパッケージでlilAM SmoothChanger1個のアバターをビルドするとクラッシュする

### ISSUE THREAD

**Issue by synqark** [lilxyzw/lilAvatarModifier#6]
Unity 2022.3.6f1
lilAvatarModifier 0.2.1 (UPM, zip展開両方）

---

本ツールをUPMからインストールし、以下の SmoothChangerのコンポーネントを設定して

<img width="640" alt="image" src="https://github.com/lilxyzw/lilAvatarModifier/assets/85712277/234d0590-c977-4a9b-bf21-720a745085a1">

SDKからBuild & Testを実行すると、以下のダイアログでUnityがクラッシュしました。

<img width="640" alt="image" src="https://github.com/lilxyzw/lilAvatarModifier/assets/85712277/c92df27d-eaf4-4f93-abb0-f82305d30c7a">

（このダイアログテキストコピーできませんでした...）

一方、README.mdに記載頂いている代替手順（[zip](https://github.com/lilxyzw/lilAvatarModifier/archive/refs/heads/main.zip)をダウンロードし、プロジェクトのPackagesフォルダ配下に配置する）でインストールした場合、
Build&Testが通り、設定内容に対応するExpressionが組み込まれたアバターを利用できることを確認済みです。

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。アニメーション関連のアセットの複製はうまくいっていてマテリアルの複製でのみクラッシュが発生しているので、アセットのサムネイルの生成のようなUnity側の処理で何らかの問題が発生していそう……？
Unityのバグのような気がしますが、こちらでもHideFlagsをいじってみるなどで回避できないか模索してみます。
正式公開する際にはvpmでの配布となり代替手順同様にzipがPackagesフォルダ配下に展開される形になるので問題を回避できるかもしれません。

**Comment by synqark** [comment]
ありがとうございます！
> 正式公開する際にはvpmでの配布となり代替手順同様～

であれば（現にzip展開で運用できているし）関連事象無さそうであればクローズでも大丈夫そうです。
何かわかればこちらも後から追記しますが、対応はお任せいたします。

**Comment by lilxyzw** [comment]
ビルド時の一時アセットの生成場所を変えたので、もしかしたらこの変更で修正されたかもしれません

**Comment by synqark** [comment]
報告時のプロジェクトで0.2.2をUPMで取得したところ、ビルドが正常に通ることが確認できました。
迅速な対応ありがとうございました！
