### ISSUE TITLE
CostumeChangerのマテリアルの置き換えを指定して実行するとエラーになる

### ISSUE THREAD

**Issue by PetankoMelonpan** [lilxyzw/lilAvatarModifier#8]
lilAvatarModifier 0.2.2
Unity 2022.3.6f1

アバター内に新しいオブジェクトを作成、そのオブジェクトにCostumeChangerコンポーネントを追加しました。
コスチュームの+ボタン、マテリアルの置き換えの+ボタンを押し、Rendererを適当に指定しました。

この状況でプレイするとエラーが発生しました。

https://github.com/lilxyzw/lilAvatarModifier/assets/161114772/99c13a7b-f256-4510-97e4-66242b3dccaa

```
InvalidOperationException: Sequence contains no matching element
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <de4a1a1490a74771a34fee0d1d586658>:0)
jp.lilxyzw.avatarmodifier.ObjHelper.GetMenuName (jp.lilxyzw.avatarmodifier.runtime.Costume costume) (at ./Packages/jp.lilxyzw.avatarmodifier/Editor/Helper/ObjHelper.Component.cs:18)
jp.lilxyzw.avatarmodifier.ObjHelper.ResolveMenuName (jp.lilxyzw.avatarmodifier.runtime.CostumeChanger[] changers) (at ./Packages/jp.lilxyzw.avatarmodifier/Editor/Helper/ObjHelper.Component.cs:32)
jp.lilxyzw.avatarmodifier.Processor.FindComponent (nadena.dev.ndmf.BuildContext ctx) (at ./Packages/jp.lilxyzw.avatarmodifier/Editor/Processor/Processor.cs:39)
jp.lilxyzw.avatarmodifier.AvatarModifierPlugin+<>c.<Configure>b__4_0 (nadena.dev.ndmf.BuildContext ctx) (at ./Packages/jp.lilxyzw.avatarmodifier/Editor/NDMF/AvatarModifierPlugin.cs:18)
nadena.dev.ndmf.AnonymousPass.Execute (nadena.dev.ndmf.BuildContext context) (at ./Packages/nadena.dev.ndmf/Editor/API/Fluent/Pass.cs:42)
nadena.dev.ndmf.ConcretePass.Execute (nadena.dev.ndmf.BuildContext context) (at ./Packages/nadena.dev.ndmf/Editor/API/Solver/PluginResolver.cs:36)
nadena.dev.ndmf.BuildContext.RunPass (nadena.dev.ndmf.ConcretePass pass) (at ./Packages/nadena.dev.ndmf/Editor/API/BuildContext.cs:337)
UnityEngine.Debug:LogException(Exception)
nadena.dev.ndmf.Plugin`1:OnUnhandledException(Exception) (at ./Packages/nadena.dev.ndmf/Editor/API/Fluent/Plugin.cs:81)
nadena.dev.ndmf.Plugin`1:nadena.dev.ndmf.IPluginInternal.OnUnhandledException(Exception) (at ./Packages/nadena.dev.ndmf/Editor/API/Fluent/Plugin.cs:86)
nadena.dev.ndmf.BuildContext:RunPass(ConcretePass) (at ./Packages/nadena.dev.ndmf/Editor/API/BuildContext.cs:341)
nadena.dev.ndmf.AvatarProcessor:ProcessAvatar(BuildContext, BuildPhase, BuildPhase) (at ./Packages/nadena.dev.ndmf/Editor/AvatarProcessor.cs:198)
nadena.dev.ndmf.VRChat.BuildFrameworkPreprocessHook:OnPreprocessAvatar(GameObject) (at ./Packages/nadena.dev.ndmf/Editor/VRChat/BuildFrameworkPreprocessHook.cs:43)
VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks:OnPreprocessAvatar(GameObject)
nadena.dev.ndmf.ApplyOnPlay:MaybeProcessAvatar(OnDemandSource, MonoBehaviour) (at ./Packages/nadena.dev.ndmf/Editor/ApplyOnPlay.cs:95)
nadena.dev.ndmf.runtime.AvatarActivator:Awake() (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:179)
UnityEngine.GameObject:AddComponent()
nadena.dev.ndmf.runtime.RuntimeUtil:GetOrAddComponent(GameObject) (at ./Packages/nadena.dev.ndmf/Runtime/RuntimeUtil.cs:33)
nadena.dev.ndmf.runtime.ApplyOnPlayGlobalActivator:Awake() (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:118)
```
I```
nvalidOperationException: Sequence contains no matching element
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <de4a1a1490a74771a34fee0d1d586658>:0)
jp.lilxyzw.avatarmodifier.ObjHelper.GetMenuName (jp.lilxyzw.avatarmodifier.runtime.Costume costume) (at ./Packages/jp.lilxyzw.avatarmodifier/Editor/Helper/ObjHelper.Component.cs:18)
jp.lilxyzw.avatarmodifier.ObjHelper.ResolveMenuName (jp.lilxyzw.avatarmodifier.runtime.CostumeChanger[] changers) (at ./Packages/jp.lilxyzw.avatarmodifier/Editor/Helper/ObjHelper.Component.cs:32)
jp.lilxyzw.avatarmodifier.Processor.FindComponent (nadena.dev.ndmf.BuildContext ctx) (at ./Packages/jp.lilxyzw.avatarmodifier/Editor/Processor/Processor.cs:39)
jp.lilxyzw.avatarmodifier.AvatarModifierPlugin+<>c.<Configure>b__4_0 (nadena.dev.ndmf.BuildContext ctx) (at ./Packages/jp.lilxyzw.avatarmodifier/Editor/NDMF/AvatarModifierPlugin.cs:18)
nadena.dev.ndmf.AnonymousPass.Execute (nadena.dev.ndmf.BuildContext context) (at ./Packages/nadena.dev.ndmf/Editor/API/Fluent/Pass.cs:42)
nadena.dev.ndmf.ConcretePass.Execute (nadena.dev.ndmf.BuildContext context) (at ./Packages/nadena.dev.ndmf/Editor/API/Solver/PluginResolver.cs:36)
nadena.dev.ndmf.BuildContext.RunPass (nadena.dev.ndmf.ConcretePass pass) (at ./Packages/nadena.dev.ndmf/Editor/API/BuildContext.cs:337)
UnityEngine.Debug:LogException(Exception)
nadena.dev.ndmf.ErrorReport:ReportError(IError) (at ./Packages/nadena.dev.ndmf/Editor/ErrorReporting/ErrorReport.cs:161)
nadena.dev.ndmf.ErrorReport:ReportException(Exception, String) (at ./Packages/nadena.dev.ndmf/Editor/ErrorReporting/ErrorReport.cs:207)
nadena.dev.ndmf.BuildContext:RunPass(ConcretePass) (at ./Packages/nadena.dev.ndmf/Editor/API/BuildContext.cs:342)
nadena.dev.ndmf.AvatarProcessor:ProcessAvatar(BuildContext, BuildPhase, BuildPhase) (at ./Packages/nadena.dev.ndmf/Editor/AvatarProcessor.cs:198)
nadena.dev.ndmf.VRChat.BuildFrameworkPreprocessHook:OnPreprocessAvatar(GameObject) (at ./Packages/nadena.dev.ndmf/Editor/VRChat/BuildFrameworkPreprocessHook.cs:43)
VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks:OnPreprocessAvatar(GameObject)
nadena.dev.ndmf.ApplyOnPlay:MaybeProcessAvatar(OnDemandSource, MonoBehaviour) (at ./Packages/nadena.dev.ndmf/Editor/ApplyOnPlay.cs:95)
nadena.dev.ndmf.runtime.AvatarActivator:Awake() (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:179)
UnityEngine.GameObject:AddComponent()
nadena.dev.ndmf.runtime.RuntimeUtil:GetOrAddComponent(GameObject) (at ./Packages/nadena.dev.ndmf/Runtime/RuntimeUtil.cs:33)
nadena.dev.ndmf.runtime.ApplyOnPlayGlobalActivator:Awake() (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:118)
```
```
The VRCSDK build was aborted because the VRCSDKPreprocessAvatarCallback 'BuildFrameworkOptimizeHook' reported a failure.
UnityEngine.Debug:LogError (object)
VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks:OnPreprocessAvatar (UnityEngine.GameObject)
nadena.dev.ndmf.ApplyOnPlay:MaybeProcessAvatar (nadena.dev.ndmf.runtime.ApplyOnPlayGlobalActivator/OnDemandSource,UnityEngine.MonoBehaviour) (at ./Packages/nadena.dev.ndmf/Editor/ApplyOnPlay.cs:95)
nadena.dev.ndmf.runtime.AvatarActivator:Awake () (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:179)
UnityEngine.GameObject:AddComponent<nadena.dev.ndmf.runtime.AvatarActivator> ()
nadena.dev.ndmf.runtime.RuntimeUtil:GetOrAddComponent<nadena.dev.ndmf.runtime.AvatarActivator> (UnityEngine.GameObject) (at ./Packages/nadena.dev.ndmf/Runtime/RuntimeUtil.cs:33)
nadena.dev.ndmf.runtime.ApplyOnPlayGlobalActivator:Awake () (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:118)
```

**Comment by lilxyzw** [comment]
バグレポートありがとうございます。
こちらのエラーはメニュー名が空っぽだった場合に表示されるのでメニュー名を設定することで回避できると思います。
devブランチにてこちらのエラー自体の修正を行い、加えてメニュー名が空っぽだった場合に警告を出すようにしました。
